name: Info AD
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      AD_ID: ${{secrets.ADMOB_CLIENT_ID}}

    steps:
      - run: export AD_CLIENT_ID=AD_ID
      - run: echo $AD_ID
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile --production
      - name: Node run
        run: node punjabits/init.js
        env:
          CI: true
          ADMOB_CLIENT_ID: ${{ secrets.ADMOB_CLIENT_ID }}
